### ISSUE TITLE
RE: скрипт выполняется без ошибок, но таблицы не создаются

### ISSUE THREAD

**Issue by undermuz** [2nikitinalexandr2/junior-php-contest#1]
Создаются, только в неверном файле, из-за некорректного составления пути: нужно использовать двойные кавычки
![image](https://user-images.githubusercontent.com/6875507/183884481-70fdc082-c775-47f5-9bed-688308a6290b.png)

![image](https://user-images.githubusercontent.com/6875507/183884394-70878e57-4ccc-4868-a59a-fb32d4431e3a.png)

**Comment by 2nikitinalexandr2** [comment]
спасибо! таблицы создались скрипт работает, продолжу, создам модели
